#!/bin/bash

# Backup configuration files
sudo cp /etc/systemd/resolved.conf /etc/systemd/resolved.conf.backup > /tmp/DNS-change-log 2>&1
sudo cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf.backup >> /tmp/DNS-change-log 2>&1
sudo cp /etc/resolv.conf /etc/resolv.conf.backup >> /tmp/DNS-change-log 2>&1

echo "Choose a DNS provider:"
echo "1. CloudFlare with Google Fallback"
echo "2. Shecan"
echo "3. Network default"

read -p "Enter your choice (1-3): " choice

if [ "$choice" == "1" ]; then
    echo -e "[Resolve]\nDNS=1.1.1.1\nFallbackDNS=8.8.8.8 8.8.4.4\nDNSStubListener=yes" | sudo tee /etc/systemd/resolved.conf >> /tmp/DNS-change-log 2>&1
    echo -e "[main]\ndns=none\nignore-auto-dns=true" | sudo tee /etc/NetworkManager/NetworkManager.conf >> /tmp/DNS-change-log 2>&1
elif [ "$choice" == "2" ]; then
    echo -e "[Resolve]\nDNS=178.22.122.100\nFallbackDNS=185.51.200.2\nDNSStubListener=no" | sudo tee /etc/systemd/resolved.conf >> /tmp/DNS-change-log 2>&1
    echo -e "[main]\ndns=none\nignore-auto-dns=true\n[connection]\nipv6.method=ignore" | sudo tee /etc/NetworkManager/NetworkManager.conf >> /tmp/DNS-change-log 2>&1
elif [ "$choice" == "3" ]; then
    echo -e "[Resolve]\nDNS=\nFallbackDNS=\nDNSStubListener=yes" | sudo tee /etc/systemd/resolved.conf >> /tmp/DNS-change-log 2>&1
    echo -e "[main]\ndns=default\nignore-auto-dns=false" | sudo tee /etc/NetworkManager/NetworkManager.conf >> /tmp/DNS-change-log 2>&1
else
    echo "Invalid choice. Please choose a number between 1 and 3."
    exit 1
fi

# Make sure /etc/resolv.conf is a symlink to the systemd-resolved stub resolver
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf >> /tmp/DNS-change-log 2>&1

# Restart the services to apply changes
sudo systemctl restart systemd-resolved >> /tmp/DNS-change-log 2>&1
sudo systemctl restart NetworkManager >> /tmp/DNS-change-log 2>&1

echo "DNS settings updated successfully."

